<?php

declare(strict_types=1);

namespace App\Enums;

enum Pattern: string
{
    case Jigsaw = 'jigsaw';
    case Overcast = 'overcast';
    case FormalInvitation = 'formalInvitation';
    case Topography = 'topography';
    case Texture = 'texture';
    case Jupiter = 'jupiter';
    case Architect = 'architect';
    case Cutout = 'cutout';
    case Hideout = 'hideout';
    case GraphPaper = 'graphPaper';
    case YYY = 'yyy';
    case Squares = 'squares';
    case FallingTriangles = 'fallingTriangles';
    case PianoMan = 'pianoMan';
    case PieFactory = 'pieFactory';
    case Dominos = 'dominos';
    case HexagonsPattern = 'hexagons';
    case CharlieBrown = 'charlieBrown';
    case Autumn = 'autumn';
    case Temple = 'temple';
    case StampCollection = 'stampCollection';
    case DeathStar = 'deathStar';
    case ChurchOnSunday = 'churchOnSunday';
    case ILikeFood = 'iLikeFood';
    case OverlappingHexagons = 'overlappingHexagons';
    case FourPointStars = 'fourPointStars';
    case Bamboo = 'bamboo';
    case BathroomFloor = 'bathroomFloor';
    case CorkScrew = 'corkScrew';
    case HappyIntersection = 'happyIntersection';
    case Kiwi = 'kiwi';
    case Lisbon = 'lisbon';
    case RandomShapes = 'randomShapes';
    case SteelBeams = 'steelBeams';
    case TinyCheckers = 'tinyCheckers';
    case WaterPump = 'waterPump';
    case Wiggle = 'wiggle';
    case BubblesBig = 'bubbles';
    case Cage = 'cage';
    case Connections = 'connections';
    case Current = 'current';
    case DiagonalStripes = 'diagonalStripes';
    case Flipped = 'flipped';
    case FloatingCogs = 'floatingCogs';
    case Glamorous = 'glamorous';
    case Houndstooth = 'houndstooth';
    case Leaf = 'leaf';
    case LinesInMotion = 'linesInMotion';
    case Lips = 'lips';
    case Polka = 'polka';
    case Signal = 'signal';
    case SlantedStars = 'slantedStars';
    case Wallpaper = 'wallpaper';
    case Anchors = 'anchorsAway';
    case Bevel = 'bevelCircle';
    case BrickWall = 'brickWall';
    case Boxes = 'boxes';
    case CircuitBoard = 'circuitBoard';
    case Chevrons = 'chevrons';
    case EndlessClouds = 'endlessClouds';
    case Eyes = 'eyes';
    case FloorTile = 'floorTile';
    case Groovy = 'groovy';
    case IntersectingCircles = 'intersectingCircles';
    case Melt = 'melt';
    case OverlappingDiamonds = 'overlappingDiamonds';
    case ParkayFloor = 'parkayFloor';
    case PixelDots = 'pixelDots';
    case Rails = 'rails';
    case Rain = 'rain';
    case Skulls = 'skulls';
    case SquaresInSquares = 'squaresInSquares';
    case Stripes = 'stripes';
    case TicTacToe = 'ticTacToe';
    case ZigZag = 'zigZag';
    case Aztec = 'aztec';
    case BankNote = 'bankNote';
    case Circles = 'circles';
    case CloudsBig = 'clouds';
    case Curtain = 'curtain';
    case DiamondsBig = 'diamonds';
    case Dirt = 'dirt';
    case FancyRectangles = 'fancyRectangles';
    case Food = 'food';
    case Hexagons2 = 'hexagons2';
    case Hive = 'hive';
    case Moroccan = 'moroccan';
    case Morphing = 'morphingDiamonds';
    case Newspaper = 'newspaper';
    case Noise = 'noise';
    case Plus = 'plus';
    case Squares2 = 'squares2';
    case Stars = 'stars';
    case Topography2 = 'topography2';
    case Volcano = 'volcano';
    case Waves = 'waves';

    public function label(): string
    {
        return match ($this) {
            self::Jigsaw => 'Jigsaw',
            self::Overcast => 'Overcast',
            self::FormalInvitation => 'Formal Invitation',
            self::Topography => 'Topography',
            self::Texture => 'Texture',
            self::Jupiter => 'Jupiter',
            self::Architect => 'Architect',
            self::Cutout => 'Cutout',
            self::Hideout => 'Hideout',
            self::GraphPaper => 'Graph Paper',
            self::YYY => 'YYY',
            self::Squares => 'Squares',
            self::FallingTriangles => 'Falling Triangles',
            self::PianoMan => 'Piano Man',
            self::PieFactory => 'Pie Factory',
            self::Dominos => 'Dominos',
            self::HexagonsPattern => 'Hexagons',
            self::CharlieBrown => 'Charlie Brown',
            self::Autumn => 'Autumn',
            self::Temple => 'Temple',
            self::StampCollection => 'Stamp Collection',
            self::DeathStar => 'Death Star',
            self::ChurchOnSunday => 'Church on Sunday',
            self::ILikeFood => 'I Like Food',
            self::OverlappingHexagons => 'Overlapping Hexagons',
            self::FourPointStars => 'Four Point Stars',
            self::Bamboo => 'Bamboo',
            self::BathroomFloor => 'Bathroom Floor',
            self::CorkScrew => 'Cork Screw',
            self::HappyIntersection => 'Happy Intersection',
            self::Kiwi => 'Kiwi',
            self::Lisbon => 'Lisbon',
            self::RandomShapes => 'Random Shapes',
            self::SteelBeams => 'Steel Beams',
            self::TinyCheckers => 'Tiny Checkers',
            self::WaterPump => 'Water Pump',
            self::Wiggle => 'Wiggle',
            self::BubblesBig => 'Bubbles',
            self::Cage => 'Cage',
            self::Connections => 'Connections',
            self::Current => 'Current',
            self::DiagonalStripes => 'Diagonal Stripes',
            self::Flipped => 'Flipped',
            self::FloatingCogs => 'Floating Cogs',
            self::Glamorous => 'Glamorous',
            self::Houndstooth => 'Houndstooth',
            self::Leaf => 'Leaf',
            self::LinesInMotion => 'Lines in Motion',
            self::Lips => 'Lips',
            self::Polka => 'Polka',
            self::Signal => 'Signal',
            self::SlantedStars => 'Slanted Stars',
            self::Wallpaper => 'Wallpaper',
            self::Anchors => 'Anchors Away',
            self::Bevel => 'Bevel Circle',
            self::BrickWall => 'Brick Wall',
            self::Boxes => 'Boxes',
            self::CircuitBoard => 'Circuit Board',
            self::Chevrons => 'Chevrons',
            self::EndlessClouds => 'Endless Clouds',
            self::Eyes => 'Eyes',
            self::FloorTile => 'Floor Tile',
            self::Groovy => 'Groovy',
            self::IntersectingCircles => 'Intersecting Circles',
            self::Melt => 'Melt',
            self::OverlappingDiamonds => 'Overlapping Diamonds',
            self::ParkayFloor => 'Parkay Floor',
            self::PixelDots => 'Pixel Dots',
            self::Rails => 'Rails',
            self::Rain => 'Rain',
            self::Skulls => 'Skulls',
            self::SquaresInSquares => 'Squares in Squares',
            self::Stripes => 'Stripes',
            self::TicTacToe => 'Tic Tac Toe',
            self::ZigZag => 'Zig Zag',
            self::Aztec => 'Aztec',
            self::BankNote => 'Bank Note',
            self::Circles => 'Circles',
            self::CloudsBig => 'Clouds',
            self::Curtain => 'Curtain',
            self::DiamondsBig => 'Diamonds',
            self::Dirt => 'Dirt',
            self::FancyRectangles => 'Fancy Rectangles',
            self::Food => 'Food',
            self::Hexagons2 => 'Hexagons 2',
            self::Hive => 'Hive',
            self::Moroccan => 'Moroccan',
            self::Morphing => 'Morphing Diamonds',
            self::Newspaper => 'Newspaper',
            self::Noise => 'Noise',
            self::Plus => 'Plus',
            self::Squares2 => 'Squares 2',
            self::Stars => 'Stars',
            self::Topography2 => 'Topography 2',
            self::Volcano => 'Volcano',
            self::Waves => 'Waves',
        };
    }
}
